# Deploy para o Firebase Hosting ao realizar merge na branch "main"

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Configuração do Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      # Instala dependências do Flutter
      - name: Install dependencies
        run: flutter pub get

      # Compila o Flutter para Web
      - name: Build Flutter Web
        run: flutter build web

      # Faz o deploy para o Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SARAH_CALBEZ }}
          channelId: live
          projectId: sarah-calbez
